#00. General Characteristics of DataSets 
- Dimensionality 
   - 데이터에 포함된 attribute 개수 
   - 차원이 높으면 분석이 좋지 않기에 차원축소 필요 
- Distribution 
   - attribute 별 분포 
   - 분포가 정규분포면 표현하기 쉬움 
   - Skewness는 분석 어렵게 함

# 01. Record Data

- 레코드의 순서 없음, 독립적임 
- 하나의 attribute 안에 value 여러 개 일수도

In [3]:
import pandas as pd 
df = pd.DataFrame({
    "성별" : ["여", "여", "남"],
    "나이" : [20,21,21]
})
df

  성별  나이
0  여  20
1  여  21
2  남  21

# 02. Graph-Based Data
- data with relationship among objects 
  - node 
  - link 
- data with objects that are graphs ex) 화학물질

In [4]:
# 노드 생성 

class Node() : 
  def __init__(self) : 
    self.data = None 
    self.link = None

# 03. Ordered Data 
- Sequential transaction Data (시간에 따른 거래 나열)
   - 타임 스탬프라고 생각하면 됨 
- Time Series Data (시간에 따라 측정, IoT) 
  - 연속적인 시간이라고 생각하면 됨 
- Sequence Data 
  - 순서에 따라 나열 
  - 꼭 시간일 필요 X 
- Spatial and spatio-temporal Data 
  - 공간 & 시간 
  - ex) 지역의 시간 별 온도 데이터